### ISSUE TITLE
Missing data splits

### ISSUE THREAD

**Issue by juliabuhmann** [guydurant/toolboxsf#1]
Thanks for the very nice repository!

I would be interested in using the new splits you proposed in the paper. I think this folder is missing: training_csvs
According to the README:
> The training/test splits used in the paper can be found in the training_csvs folder.

Thanks for your help!

**Comment by guydurant** [comment]
Ah apologies! The training_csvs are actually now in a folder called toolboxsf_training_csvs which is zipped in the Zenodo repo (toolboxsf_training_csvs.zip).

https://zenodo.org/records/8410136

I will change the README to reflect this.
